### ISSUE TITLE
proxy.ustclug.org 没法缓存

### ISSUE THREAD

**Issue by jiacai2050** [ustclug/mirrorrequest#154]
相关：https://github.com/jiacai2050/gooreplacer/issues/47

**Comment by zhsj** [comment]
![image](https://user-images.githubusercontent.com/227180/32529685-d43aaa24-c474-11e7-8aa2-c126c7791bde.png)

并没有任何问题

**Comment by knight42** [comment]
http header 中的字段名是 case-insensitive 的，这不是问题的原因。

导致这个问题的真正原因是，我在 nginx 中设置了 `expires 12h` 覆盖了原 response 中的 `cache-control`。而原 `cache-control` 中的 `max-age` 是 31536000，远比 12h 大，使得 response 中的 `age` 有很大可能超过 12h，让浏览器认为 cache 已经 stale 了。

现在我把 nginx 配置中的 `expires` 去掉了，尊重原 response 中的 `cache-control`，你可以再试试。

**Comment by jiacai2050** [comment]
你好，貌似还是不行，
- https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js

单独打开这个js，第一次是200，后面都是304，与之对应的

- https://ajax.proxy.ustclug.org/ajax/libs/jquery/1.12.4/jquery.min.js

每次打开都是200，麻烦再排查一下。谢谢

**Comment by knight42** [comment]
唔... HTTP 的 conditional request 跟 "浏览器究竟有没有缓存到" 不是一回事。

你提到的返回 304 是因为我们 nginx 返回的响应中把 `last-modified` 这个 header 去掉了，所以后续的请求中就不会带有 `if-modified-since` 这个 header，服务器自然也不会返回 304 了。

至于 nginx 为什么会把 `last-modified` 这个 header 去掉，一是因为我们对响应的内容做了一些修改，这样原响应中的 `last-modified` 就失去意义了，二是我们用了 nginx [第三方的模块](https://github.com/yaoweibin/ngx_http_substitutions_filter_module) 做替换，它没有提供选项保留原响应中的 `last-modified`，已经有人提出了 [issue](https://github.com/yaoweibin/ngx_http_substitutions_filter_module/issues/23)。

至于究竟有没有缓存到，你可以把 url 写到一个网页的 `script` tag 里，然后打开浏览器的调试器，观察一下响应是来自网络还是本地的（如果是 chrome 的话，观察前记得别禁用 cache）。

**Comment by jiacai2050** [comment]
把 JS 放到 script 引用是能 cache 的，返回：
- Status Code:200  (from memory cache)

多谢。

**Comment by wxf4150** [comment]
看到 expires  调成 1年了.  
 估计是这个起作用了, script 的js引用 才显示了 "Status Code:200 (from memory cache)"
