### ISSUE TITLE
[New] 请求添加 antergos 镜像

### ISSUE THREAD

**Issue by dongfengweixiao** [ustclug/mirrorrequest#5]
antergos是一个基于ArchLinux的发行版，其主页为 antergos.com ，之前在国内，北京交通大学的镜像有同步踏的源，无奈现在北京交通大学的源已经死掉了。antergos 本身的源的下载速度实在是太慢。所以提交请求。以下是官方源的同步地址：
Server = http://mirrors.antergos.com/$repo/$arch

**Comment by snachx** [comment]
同求，成为官方认证源的方法请参见 [New Mirror Guidelines](https://antergos.com/wiki/miscellaneous/new-mirror-guidelines/)

**Comment by eailfly** [comment]
同求，arch的安装过程太痛苦了

**Comment by xiangjf** [comment]
@eailfly 安装其实还好，主要是自己装起来的不用人家包装过的好看，哈哈，但是为了好看去各种折腾配置有太麻烦。

**Comment by wsxy162** [comment]
这边的 issue 可以 +1 吧。

**Comment by wagaaa** [comment]
#### 项目名称与简介(Project Intro.)
 
## Name: Antergos Linux

Or Antergos

## Introduce: 

Essentials Included
Antergos includes everything you need. Its default configuration provides you with a ready-to-use system. No additional steps are required after installation. You’ll be able to surf the web, listen to music, watch videos, and do anything else you like. Simply reboot your system and enjoy.

Rolling Release
Antergos is a rolling release distribution. Your entire system, from the base OS components to the applications that you install, will receive updates as they are released upstream—with only a minimal delay to ensure stability.

Multilingual
Antergos is available in many languages including Spanish, Galician, Catalan, English, German, and more.
Easily install Antergos with our Multilingual Live Medium which includes our easy-to-use graphical installer.
## 上游地址与镜像方法(How to Mirror)

### Adding a new mirror

This article outlines the procedure for adding a new mirror for Antergos packages/releases to antergos-mirrorlist.

### 2-Tier Mirroring Scheme

Due to high load and bandwidth limits, Antergos uses a 2-tier mirroring scheme. There are few **tier 1** mirrors that sync directly from  repo.antergos.com  every hour. All other mirrors are **tier 2** and should sync from one of the **tier 1** mirrors. Syncing from  repo.antergos.com by a **tier 2** mirror is not allowed.

### Mirror Administrators

Please open an issue on the [antergos-packages github repo ](https://github.com/Antergos/antergos-packages/issues/) with a request to become an authorized mirror. Please include the following in your request:
* Mirror domain name
* Geographical location of the mirror
* Supported access methods (http, ftp, rsync, ...)
* URLs for the above access methods
* The name of the tier 1 mirror you are syncing from.
* An administrative contact email

To provide consistent mirroring and keep the upstream mirrors' load as low as possible, please ensure the following:
* Sync all contents of the upstream mirror (eg. do not sync only some repositories).
* Use the following command arguments when running rsync:

`--verbose --recursive --times --safe-links --delay-updates --delete-after --hard-links --ignore-times`

* Do not sync more than once per hour.
* Sync on a random minute so it is more likely the requests will be spaced out amongst other mirrors.
Tier-1 Mirrors

### Tier-1 Mirror	Location	Url
 mirrorservice.org	 United Kingdom |	rsync://rsync.mirrorservice.org/repo.antergos.com/ |
 leaseweb.net	 United States |	rsync://mirror.us.leaseweb.net/antergos |
 leaseweb.net 	Germany	rsync://mirror.de.leaseweb.net/antergos
 leaseweb.net	 Netherlands	rsync://mirror.nl.leaseweb.net/antergos

###Antergos Mirror Administrator

* Add the mirror info to the Mirrorbrain database and enable it
* Rebuild the antergos-mirrorlist package

## 其他信息(Other)
- 镜像大小(Mirror Size): 

To give you an idea of how much space will be needed for a mirror, here are some numbers:
* antergos: < 4GB
* antergos-staging: < 1GB
* iso: < 5GB


---
https://antergos.com/wiki/miscellaneous/new-mirror-guidelines/

by Wagaaa Markdown version.

**Comment by knight42** [comment]
给官方提了 [issue](https://github.com/Antergos/antergos-packages/issues/113)

现在已经可以通过 http://mirrors.ustc.edu.cn/antergos 来访问, 提供 http(s), rsync

同步周期为 4 小时一次
